[package]
name = "corda-ibc-client"
version = "0.1.0"
authors = ["YOSHIDA Masanori <masanori.yoshida@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "1"
prost = "0.7"
prost-types = "0.7"

[build-dependencies]
prost-build = { version = "0.7" }
