name: Corda-IBC Test
on: [push, pull_request]
jobs:
  relayer-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: make testRelayerBuild
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Contract testing
        run: make testContracts
      - name: Flow testing
        run: make testFlows
  e2e-test:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Build the client written in Rust
        run: make buildClient
      - name: Build the Docker image of the client
        run: make buildClientImage
      - name: Build the Docker image of the Corda network (notary and participant nodes)
        run: make buildImage
      - name: Test handshake
        run: make test
      #- name: Test handshake + token transfer
      #  run: make oldTest
